### ISSUE TITLE
多余了一个‘juejin’

### ISSUE THREAD

**Issue by kenshinji** [chengsixgoold/juejin#7]
敲了`juejin --help `之后显示如下，很明显多余了一个juejin

<img width="387" alt="screen shot 2018-03-02 at 09 53 44" src="https://user-images.githubusercontent.com/1403893/36879622-aecdccaa-1dff-11e8-8e6d-8fe188a3c4a4.png">

**Comment by kenshinji** [comment]
已提PR https://github.com/chengsixgoold/juejin/pull/8

**Comment by ihoey** [comment]
感谢~
